# ИМЕ НА АПЛИКАЦИЈАТА
spring.application.name=job-portal

# POSTGRESQL БАЗА
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/job_portal_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ПОРТА НА СЕРВЕРОТ (за да не се тепа со React)
server.port=8081

# SPRING AI OLLAMA (Вештачка Интелигенција)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:llama3}
spring.ai.ollama.chat.enabled=true